# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:06:11+00:00

from __future__ import annotations

from typing import List

from pydantic import RootModel

from . import Type8


class JsonGetResponse(RootModel[List[Type8]]):
    root: List[Type8]
