# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:06:11+00:00

from __future__ import annotations

from typing import Union

from pydantic import RootModel

from . import NewPartnerStore, PartnerStoreStatus


class JsonGetResponse(RootModel[Union[PartnerStoreStatus, NewPartnerStore]]):
    root: Union[PartnerStoreStatus, NewPartnerStore]
